ReachYourGoals/config/routes.rb
Rails.application.routes.draw do

  resources :users

  resource :session

  resources :goals

  resources :user_comments

  resources :goal_comments

end

ReachYourGoals/app/models/goal.rb
class Goal < ActiveRecord::Base

  validates :name, :user_id, presence: true

  belongs_to :user

  has_many :comments,
    class_name: "GoalComment",
    foreign_key: :goal_id,
    primary_key: :id


end

ReachYourGoals/app/models/goal_comment.rb
class GoalComment < ActiveRecord::Base
  validates :body, :author_id, :goal_id, presence: true

  belongs_to :author,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id

  belongs_to :goal,
    class_name: "Goal",
    foreign_key: :goal_id,
    primary_key: :id

end

ReachYourGoals/app/models/user.rb
class User < ActiveRecord::Base

  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token

  attr_reader :password

  has_many :goals

  has_many :received_comments,
    class_name: "UserComment",
    foreign_key: :recipient_id,
    primary_key: :id

  has_many :sent_comments,
    class_name: "UserComment",
    foreign_key: :author_id,
    primary_key: :id

    has_many :goal_comments,
      class_name: "GoalComment",
      foreign_key: :author_id,
      primary_key: :id


  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    @user = User.find_by_username(username)

    return nil unless @user

    if @user.is_password?(password)
      @user
    else
      nil
    end
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end
end

ReachYourGoals/app/models/user_comment.rb
class UserComment < ActiveRecord::Base
  validates :body, :author_id, :recipient_id, presence: true

  belongs_to :author,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id

  belongs_to :recipient,
    class_name: "User",
    foreign_key: :recipient_id, 
    primary_key: :id

end

ReachYourGoals/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :logged_in?

  def logged_in?
    !!current_user
  end

  def require_logged_in
    unless logged_in?
      redirect_to new_session_url
    end
  end

  def log_in(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def log_out!
    current_user.reset_session_token!

    session[:session_token] = nil
  end

end

ReachYourGoals/app/controllers/goal_comments_controller.rb
class GoalCommentsController < ApplicationController

  before_action :require_logged_in

  def create
    @goal_comment = GoalComment.new(goal_comment_params)
    @goal_comment.author_id = current_user.id
    @goal_comment.save
    flash[:errors] = @goal_comment.errors.full_messages
    redirect_to goal_url(@goal_comment.goal)
  end

  def destroy
    @goal_comment = GoalComment.find(params[:id])
    @goal_comment.destroy
    redirect_to goal_url(@goal_comment.goal)
  end

  private

  def goal_comment_params
    params.require(:goal_comment).permit(:body, :author_id, :goal_id)
  end

end

ReachYourGoals/app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  before_action :require_logged_in, only: [:new,:create,:update]

  def index
    @goals = Goal.all
    render :index
  end

  def new
    @goal = Goal.new
    render :new
  end

  def create
    @goal = current_user.goals.new(goal_params)
    if @goal.save
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update_attributes(goal_params)
      redirect_to goals_url
    else
      redirect_to goals_url
    end
  end

  def show
    @goal = Goal.find(params[:id])
    render :show
  end

  private

    def goal_params
      params.require(:goal).permit(:name, :private, :completed)
    end

end

ReachYourGoals/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(session_params[:username], session_params[:password])

    if @user
      log_in(@user)
      redirect_to goals_url
    else
      render :new
    end
  end

  def destroy
    @user = User.find_by_session_token(session[:session_token])
    log_out!

    redirect_to new_session_url
  end

  private
    def session_params
      params.require(:session).permit(:username,:password,:session_token)
    end

end

ReachYourGoals/app/controllers/user_comments_controller.rb
class UserCommentsController < ApplicationController

  before_action :require_logged_in

  def create
    @user_comment = UserComment.new(user_comment_params)
    @user_comment.author_id = current_user.id
    @user_comment.save
    flash[:errors] = @user_comment.errors.full_messages
    redirect_to user_url(@user_comment.recipient)
  end

  def destroy
    @user_comment = UserComment.find(params[:id])
    @user_comment.destroy
    redirect_to user_url(@user_comment.recipient)

  end



  private

    def user_comment_params
      params.require(:user_comment).permit(:body, :author_id, :recipient_id)
    end

end

ReachYourGoals/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end


  def show
    @user = User.find(params[:id])
    # @user_comment = @user.sent_coments.new()
    render :show
  end



  private

    def user_params
      params.require(:user).permit(:username, :password)
    end

end

ReachYourGoals/app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
  end
end

ReachYourGoals/app/helpers/goal_comments_helper.rb
module GoalCommentsHelper
end

ReachYourGoals/app/helpers/goals_helper.rb
module GoalsHelper
end

ReachYourGoals/app/helpers/sessions_helper.rb
module SessionsHelper
end

ReachYourGoals/app/helpers/user_comments_helper.rb
module UserCommentsHelper
end

ReachYourGoals/app/helpers/users_helper.rb
module UsersHelper
end

ReachYourGoals/app/views/goals/index.html.erb
<h1>All Goals</h1>

<% @goals.each do |goal| %>
  <ul>
    <% next if goal.private && (current_user.nil? || current_user.id != goal.user_id) %>
    <li>
      <%= link_to goal.user.username, user_url(goal.user) %>
      <%= link_to goal.name, goal_url(goal) %>
      <%= goal.completed ? "Goal Completed!" : "Not Completed" %>
      <% if !goal.completed && current_user == goal.user   %>
            <form action="<%= goal_url(goal) %>" method="POST">
            <input
              type="hidden"
              name="authenticity_token"
              value="<%= form_authenticity_token %>">

            <input type="hidden" name="_method" value="PATCH">
            <input type="hidden" name="goal[completed]" value="true">
            <input type="submit" value="Goal Completed">

            </form>
            <% end %>

    </li>
  </ul>
<% end %>


<%= link_to "New Goal", new_goal_url %>

ReachYourGoals/app/views/goals/new.html.erb
<h1>Enter New Goal</h1>

<form action="<%=goals_url%>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label>Description
    <input
      type="text"
      name="goal[name]"
      value="<%= @goal.name %>">
  </label>
  <br>
  <label>Make Goal Public
    <input
      type="radio"
      name="goal[private]"
      value="false">
  </label>
  <br>

  <input type="submit" value="Create Goal">

</form>

ReachYourGoals/app/views/goals/show.html.erb
<h1><%= @goal.name %></h1>

<% @goal.comments.each do |comment| %>
  <ul>
    <li>
      <%= comment.body %>
      <% if current_user == comment.author %>
      <%= button_to "Delete Comment", goal_comment_url(comment), method: :delete %>
      <% end %>
    </li>
  </ul>

<% end %>

<form action="<%= goal_comments_url %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  <input
    type="hidden"
    name="goal_comment[goal_id]"
    value="<%= @goal.id %>">

    <label>
      Comment:
      <textarea
        name="goal_comment[body]"
        value="">
      </textarea>
    </label>

    <input type="submit" value="Submit Comment">

</form>

<%= link_to "All da Goals", goals_url %>

ReachYourGoals/app/views/layouts/_errors.html.erb
<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>

ReachYourGoals/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReachYourGoals</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


</head>
<body>
  <%= render "layouts/errors" %>

  <% if logged_in? %>
    Welcome <%= current_user.username %>
    <%= button_to "Sign Out", session_url, method: :delete %>
  <% else %>
    <%= link_to "Sign Up", new_user_url %>
    <%= link_to "Sign In", new_session_url %>
  <% end %>

<%= yield %>

</body>
</html>

ReachYourGoals/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%=users_url%>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">


<label>
  Username
  <input
    type="text"
    name='user[username]'
    value="<%= @user.username %>">
</label>

<label>
  Password
  <input
    type="text"
    name='user[password]'
    value="<%= @user.password %>">
</label>

<input type="submit" value="Sign Up">

</form>

ReachYourGoals/app/views/users/show.html.erb
<h1> <%= @user.username %> </h1>


<% @user.received_comments.each do |comment| %>
  <ul>
    <li>
      <%= comment.body %>
    </li>
  </ul>

<% end %>

<form action="<%= user_comments_url %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  <input
    type="hidden"
    name="user_comment[recipient_id]"
    value="<%= @user.id %>">

    <label>
      Comment:
      <textarea
        name="user_comment[body]"
        value="">
      </textarea>
    </label>

    <input type="submit" value="Submit Comment">

</form>